DEFAULT_BRANCH: devel
VALIDATE_ALL_CODEBASE: false
CLEAR_REPORT_FOLDER: true
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
GITHUB_COMMENT_REPORTER: false
MARKDOWN_SUMMARY_REPORTER: true

ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - YAML_YAMLLINT

ENABLE_ERRORS_LINTERS:
  - ACTION_ACTIONLINT
  - YAML_YAMLLINT

EXCLUDED_DIRECTORIES:
  - .git
  - megalinter-reports
  - bags
  - logs

BASH_SHELLCHECK_ARGUMENTS: >-
  --external-sources
  --exclude=SC1091
