version: '3.9'
services:
  nav_cont:
    image: ${REGISTRY_HOST}/${IMAGE_OWNER}/nav:${NAV_TAG}
    container_name: nav_cont
    network_mode: host  # ROS 2 koristi DDS, koji zahtijeva host mrežu
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    depends_on:
      - database_cont
      - slam_cont
      - rosbridge_websocket
    restart: always

  database_cont:
    image: ${REGISTRY_HOST}/${IMAGE_OWNER}/db:${DB_TAG}
    container_name: database_cont
    network_mode: host
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /srv/db
    volumes:
      - ./srv:/srv
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 5

  laser_driver:
    image: ${REGISTRY_HOST}/${IMAGE_OWNER}/driver:${DRIVER_TAG}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0  # Mora biti isti kao u rosbridge_websocket
    container_name: laser_driver_cont
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Mapiranje serijskog uređaja
    network_mode: host  # ROS 2 koristi DDS, koji zahtijeva host mrežu
    depends_on:
      - database_cont
    restart: always

  slam_cont:
    image: ${REGISTRY_HOST}/${IMAGE_OWNER}/slam:${SLAM_TAG}
    container_name: slam_cont
    network_mode: host  # ROS 2 zahtijeva host mrežu
    depends_on:
      - database_cont
    volumes:
      - ./config/slam_params.yaml:/app/slam_params.yaml  # Konfiguracija
      - ./srv:/srv  # Trajni podaci (maps & ostalo)
    environment:
      - MAP_ROOT=${MAP_ROOT}
      - DB_HOST=localhost
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f slam_toolbox >/dev/null || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5

  rosbridge_websocket:
    image: ${REGISTRY_HOST}/${IMAGE_OWNER}/rosbridge:${ROSBRIDGE_TAG}
    container_name: rosbridge_websocket_cont
    environment:
      - ROS_DOMAIN_ID=0  # Postavi isti ROS_DOMAIN_ID za sve containere
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    ports:
      - "9090:9090"  # Standardni port za rosbridge websocket
    network_mode: host  # ROS 2 koristi DDS, koji zahtijeva host mrežu
    restart: always

  sensor_fusion_cont:
    image: ${REGISTRY_HOST}/${IMAGE_OWNER}/sensor_fusion:${SENSOR_FUSION_TAG}
    container_name: sensor_fusion_cont
    network_mode: host
    restart: always
    depends_on:
      - database_cont
      - slam_cont

volumes: {}

