- /scan_filtered

- /odom_rf2o
- /odometry/filtered
- /amcl_pose
- /robot_pose_map

- /tf
- /tf_static
- /map

- /cmd_vel
- /cmd_vel_auto
- /cmd_vel_nav
- /cmd_vel_smoothed
- /cmd_vel_collision_in
- /cmd_vel_safety_in
- /cmd_vel_safety_status

- /imu/base_link_corrected

- /motor_pwm
- /robot_status

- /plan
- /smoothed_path
- /local_plan

- /collision_monitor_state
- /experiment_event

- /anomaly/events
- /anomaly/events/readable
- /anomaly/markers
- /anomaly/inspection/status
- /anomaly/inspection/result